source 'https://rubygems.org'

gem 'em-websocket', '~> 0.5.1'
gem 'em-pg-client', '~> 0.3.4'
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Unicorn for our web server
gem 'unicorn'
# And Thin as our backup
gem 'thin'

gem 'activesupport', '~>7.0'
gem 'activerecord', '~>7.0'
gem 'bcrypt-ruby', '~> 3.1.5'

gem 'rake'

gem 'rspec'

gem 'faker'

gem 'encryptor'
